language: cpp
sudo: false

addons:
  apt:
    packages:
    - swig
    - python-dev
    - python3-dev
    - libusb-dev

install:
  - git clone https://github.com/nfc-tools/libnfc.git
  - pushd libnfc
  - git checkout tags/libnfc-1.7.1
  - cmake -DCMAKE_INSTALL_PREFIX=~/.local/ .
  - make install -j2
  - popd

script:
  - cmake -DCMAKE_INSTALL_PREFIX=~/.local/ -DPYTHON_EXECUTABLE=/usr/bin/python2 .
  - make install -j2
  - LD_LIBRARY_PATH=~/.local/lib/ python2 python/examples/quick_start_example.py || echo "nop"
  - rm CMakeCache.txt
  - cmake -DCMAKE_INSTALL_PREFIX=~/.local/ -DPYTHON_EXECUTABLE=/usr/bin/python3 .
  - make install -j2
  - LD_LIBRARY_PATH=~/.local/lib/ python3 python/examples/quick_start_example.py || echo "nop"
