language: cpp
before_install:
  - sudo apt-get install libusb-dev
  - git clone https://code.google.com/p/libnfc/ && pushd libnfc && cmake -DCMAKE_INSTALL_PREFIX=$PWD/install && make install && popd
  - sudo apt-get install swig python-dev
compiler: gcc

before_script:
  - mkdir build && pushd build

script:
  - cmake -DCMAKE_INSTALL_PREFIX=$PWD/install -DLIBNFC_LIBRARY=$PWD/../libnfc/install/lib/libnfc.so -DLIBNFC_INCLUDE_DIR=$PWD/../libnfc/install/include .. && make install
