language: cpp
before_install: sudo apt-get install swig python-dev
compiler:
  - gcc
  - clang

before_script:
  - mkdir build && cd build

script:
  - cmake -DCMAKE_INSTALL_PREFIX=$PWD/install .. && make install
