language: cpp
sudo: no

addons:
  apt:
    packages:
    - swig
    - python-dev
    - libusb-dev

before_install:
  - git clone https://github.com/nfc-tools/libnfc.git
  - pushd libnfc
  - git checkout tags/libnfc-1.7.1
  - cmake -DCMAKE_INSTALL_PREFIX=~/.local/ .
  - make install -j2
  - popd

script:
  - cmake -DCMAKE_INSTALL_PREFIX=~/.local/ -DLIBNFC_LIBRARY=~/.local/lib/libnfc.so -DLIBNFC_INCLUDE_DIR=~/.local/include .
  - make install -j2
  - LD_LIBRARY_PATH=~/.local/lib/ python ../python/examples/quick_start_example.py
