language: cpp
sudo: false

addons:
  apt:
    packages:
    - swig
    - python-dev
    - libusb-dev

install:
  - git clone https://github.com/nfc-tools/libnfc.git
  - pushd libnfc
  - git checkout tags/libnfc-1.7.1
  - cmake -DCMAKE_INSTALL_PREFIX=~/.local/ .
  - make install -j2
  - popd

script:
  - cmake -DCMAKE_INSTALL_PREFIX=~/.local/ .
  - make install -j2
  - LD_LIBRARY_PATH=~/.local/lib/ python python/examples/quick_start_example.py || echo "nop"
